### PR TITLE
better warc support

### PR DESCRIPTION
**Pull request by b5**
This PR brings general interoperability with the python pywb & warcio libraries, bringing archival rewriting tools

### CODE REVIEW

**Review by titaniumbones — COMMENTED** [review]
looks cool (if way above my pay grade!) 

you rename `readme.md --> warc/readme.md`. Is that on purpose? If not want to move it back & then I can add @allenpg's changes on top of this branch?

**Comment by b5** [comment]
yeah that readme move was intentional. I'm making `warc` a subpackage, and the readme.md correspond with that package

**Comment by b5** [comment]
ok, this is now updated & ready for review. Along the way I decided to split up warc support into a bunch of different packages, so this PR is much smaller now

**Comment by b5** [comment]
ok I'm going to go ahead & merge this as it's wildly ahead of master, and I can't get other test suites to pass without merging this.

**Pull request merged**
